### ISSUE TITLE
Flag to filter report for genomic/non-genomic audience

### ISSUE THREAD

**Issue by fmaguire** [pha4ge/hAMRonization#52]
For the interactive report or tabular report possibly have an option to just summarise results (genome, gene, tool, versions, phenotype annotation) and the full genomics results (i.e., the whole spec with start/stop contig coverage etc).

**Comment by fmaguire** [comment]
Requires consensus on a list of fields of use for non-genomics audience, hopefully discussion will come out of PAHO trial.

**Comment by cimendes** [comment]
Should this be integrated in the scheme validation? (related to #6)

**Comment by fmaguire** [comment]
Nah, its just a convenience feature for the interactive HTML report.

**Comment by fmaguire** [comment]
This is a whole other (many ongoing) project(s) I've come to think!

**Comment by zwets** [comment]
> This is a whole other (many ongoing) project(s) I've come to think!

Yes, but seems to relate to an issue that came up when I was updating the ResFinder backend: to what level do I aggregate when outputting each results record?

ResFinder's JSON output has a graph (or entity-relation) structure, with three core entities: phenotype, region/gene, and variant/SNP. All have M:N relations. So I could "flatten" this in multiple ways into result records:

- Per detected phenotype / antibiotic (aggregating the genes and mutations contributing to it)
- Per detected region/gene (and aggregate its multiple phenotypes and variants found on it)
- Per unique gene x phenotype combination (giving a lot of output records, later to be aggregated)
- Adding in variants/SNPs it gets even worse: aggregate by gene they were found on, or by gene x phenotype, or do I output each individually? (They're tricky anyway because it you may need a bunch of SNPs to occur all at the same time.)

This was hairier than I'd hoped. Do you have any guidance on this? (Sorry for hijacking this closed thread but this may have been answered before.)
